# inherit_from: https://git.effilab-local.com/world/style-guide/raw/rubocop-v2/ruby/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - '**/db/**/*'
    - '**/marx/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - '**/bin/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: "double_quotes"
Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Max: 200
Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  Max: 40
  ExcludedMethods:
    - 'included'
    - 'draw'
    # RSPEC
    - 'describe'
    - 'context'
    - 'shared_examples'
    - 'shared_context'
    - 'before'
    - 'it'
    - 'define'
    - 'factory'
