---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout

      - run:
          name: Update system gems
          command: |-
            sudo gem update --system
            sudo gem update --force

      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile" }}
            - v1-bundle-

      - run:
          name: Install gems
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle

      - run:
          name: Lint codebase
          command: |
            bundle exec rubocop

      - restore_cache:
          keys:
            - &coverage_cache_key v1-coverage-{{ .Branch }}-

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml

      - save_cache:
          key: v1-coverage-{{ .Branch }}-{{ epoch }}
          paths:
            - ./coverage

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  update_documentation:
    docker:
      - image: ruby:2.6.3-alpine
    steps:
      - checkout

      - run:
          name: Install envkey-source
          command: |-
            apk add --no-cache wget
            CURDIR="$(pwd)"
            TMPDIR="$(mktemp -d)"
            cd "$TMPDIR"
            wget -qO eks.tar.gz "https://github.com/envkey/envkey-source/releases/download/v1.2.9/envkey-source_1.2.9_linux_amd64.tar.gz"
            echo "d36a70d63b012f9a50260d63be31adde659da76a9730ee45fef6e98de4f9268c  eks.tar.gz" | sha256sum -c -
            tar xf eks.tar.gz envkey-source
            mv envkey-source /usr/local/bin/
            cd "$CURDIR"
            rm -rf "$TMPDIR"
            unset CURDIR TMPDIR

      - run:
          name: Generate YARD documentation
          command: |-
            gem install yard --no-document
            yard doc

      - restore_cache:
          name: Generate SimpleCov documentation
          keys:
            - *coverage_cache_key

      - run:
          name: Install mirroring step dependencies
          command: |-
            apk add --no-cache bash openssh lftp

      - run:
          name: Prepare mirroring step environment
          shell: bash
          command: |-
            export APP=fea

            case "$CIRCLE_BRANCH" in
              master) export DOCS_ENVKEY="$PRODUCTION_DOCS_ENVKEY" ;;
              fea)    export DOCS_ENVKEY="$PREPROD_DOCS_ENVKEY"    ;;
              *)      exit 1 ;;
            esac

            for var in APP DOCS_ENVKEY
            do
              declare -p $var >> $BASH_ENV
            done

      - run:
          name: Mirror docs to remote website
          shell: bash
          command: |-
            eval "$(envkey-source "$DOCS_ENVKEY")"
            .circleci/mirror_docs.sh /home/circleci/project/coverage doc/yard

workflows:
  version: 2
  create:
    jobs:
      - build
      - update_documentation:
          requires: [build]
          filters:
            branches:
              only:
                - fea
                - master
